### ISSUE TITLE
Where are the colors stored for the scrollbar?

### ISSUE THREAD

**Issue by phoen1x74** [smealum/3ds_hb_menu#60]
Working on a pretty basic theme, and am just wondering where the god damned scroll bar colors are stored. 
![2ed8471d-7c1d-4f04-9256-ef8d9e295696146649806](https://cloud.githubusercontent.com/assets/23296494/21033731/b12fe19e-bd80-11e6-8d6d-cfdee9845242.jpg)

**Comment by suloku** [comment]
drawScrollBar() in menu.c

I made a mod long ago, it had xml theme support, amongst other things, but it went too far apart the original hbl, but I think it still holds up to date and I added mmap support.
But I think I was using too much memory (or non optimized code) and gives problems on o3DS (works fine on my n3DS though, but I don't use it much since CFW.
https://github.com/suloku/3ds_hb_menu/tree/patch-1
